#!/bin/sh
# Prevent repeated starts
PID=$$
readonly TMP_PATH=/tmp/${PID}
readonly LOCK=/var/lock/adblock.lock
if [ -f $LOCK ]; then
    case $1 in
    gen | addown) X=1 ;;
    *) exit 1 ;;
    esac
fi
touch $LOCK

B="Download Subscribe Rules"
FMT_DT="date +'%Y-%m-%d %H:%M:%S'"
_3RD_URL="$(uci -q get adblock.@adblock[0].url)"
AD_WORK_PATH=/tmp/adblock
WT_FILE=/etc/adblock/white.list

gen() {
    grep -e "^||[^*]*^$" /tmp/adnew.conf |
        grep -Ev "^\|\|[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}*" |
        sed -e 's:||:address=/:' -e 's:\^:/:' >/tmp/ad.conf
    while IFS= read -r line; do
        sed -i -e "/\/$line\//d" -e "/\.$line\//d" /tmp/ad.conf
    done <${WT_FILE}
    rm -f /tmp/adnew.conf
}

down() {
    down_tmp_path=/tmp/ad_tmp/3rd
    tmp_ad_new=$down_tmp_path/ad_new.conf
    rm -rf ${down_tmp_path%/*}
    mkdir -p $down_tmp_path
    count_url=0
    for url in $_3RD_URL; do
        times=20
        while ! uclient-fetch \
            --no-check-certificate \
            --timeout=5 --continue --quiet -O $tmp_ad_new "$url"; do
            [ $times -le 0 ] &&
                echo "$(eval "$FMT_DT") [Download $url Failed]" &&
                continue 2 || times=$((times - 1))
            sleep 2
        done
        X=$(md5sum $down_tmp_path/3rd.conf 2>/dev/null | awk '{print$1}')
        Y=$(md5sum $down_tmp_path/host 2>/dev/null | awk '{print$1}')
        sed -i 's/\r/\n/g' $tmp_ad_new
        sed -i -e '/127.0.0.1 #/d' -e '/127.0.0.1 !/d' -e 's:#.*::' \
            -e 's:!.*::' -e 's/\$.*//g' -e 's/[ \t]*$//g' -e 's/^[ \t]*//g' \
            -e '/\*/d' -e '/^$/d' $tmp_ad_new
        if grep -q "^address=" $tmp_ad_new; then
            cat $tmp_ad_new >>$down_tmp_path/3rd.conf
        elif grep -q -e "^0.0.0.0 " -e "^127.0.0.1 " $tmp_ad_new; then
            cat $tmp_ad_new >>$down_tmp_path/host
        elif ! grep -q -e "|" -e "@" $tmp_ad_new; then
            sed -e 's:^:address=/:' -e 's:$:/:' <$tmp_ad_new >>$down_tmp_path/3rd.conf
        else
            grep -e "^||[^*]*^$" ${tmp_ad_new} |
                grep -Ev "^\|\|[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}*" |
                sed -e 's:||:address=/:' -e 's:\^:/:' >>$down_tmp_path/3rd.conf
        fi
        [ "$X" = "$(md5sum $down_tmp_path/3rd.conf 2>/dev/null | awk '{print$1}')" -a \
            "$Y" = "$(md5sum $down_tmp_path/host 2>/dev/null | awk '{print$1}')" ] &&
            echo "$(eval "$FMT_DT") [Conversion $url Failed]"
        echo "$url" >>$down_tmp_path/url
        count_url=$((count_url + 1))
    done
    [ -s $down_tmp_path/host ] && sed -e '/:/d' -e '/ 0.0.0.0/d' -e '/255.255.255.255/d' \
        -e '/ local/d' -e 's:127.0.0.1 :address=/:' -e 's:0.0.0.0 :address=/:' -e 's:$:/:' \
        $down_tmp_path/host >>$down_tmp_path/3rd.conf
    mkdir -p ${TMP_PATH}
    [ -s $down_tmp_path/3rd.conf ] && sed -i -e 's:/127.0.0.1$:/:' -e 's:/0.0.0.0$:/:' \
        $down_tmp_path/3rd.conf && [ "$count_url" -gt 1 ] &&
        sort -u $down_tmp_path/3rd.conf >${TMP_PATH}/tmp_3rd &&
        mv ${TMP_PATH}/tmp_3rd $down_tmp_path/3rd.conf
    [ -s $down_tmp_path/url ] && sort -u $down_tmp_path/url >${TMP_PATH}/tmp_url &&
        mv ${TMP_PATH}/tmp_url $down_tmp_path/url
    rm -rf ${TMP_PATH}

    if [ -s $down_tmp_path/3rd.conf ]; then
        echo "$(eval "$FMT_DT") [$B Successful]"
        rm -f $tmp_ad_new $down_tmp_path/host $AD_WORK_PATH/failed
        while IFS= read -r line; do
            sed -i -e "/\/$line\//d" -e "/\.$line\//d" $down_tmp_path/3rd.conf
        done <${WT_FILE}
        X=$(uci -q get adblock.@adblock[0].flash)
        new_md5=$(md5sum $down_tmp_path/* | awk '{print$1}')
        [ "$X" = 0 ] && old_md5=$(md5sum $AD_WORK_PATH/3rd/* 2>/dev/null | awk '{print$1}') ||
            old_md5=$(md5sum /etc/adblock/3rd/* 2>/dev/null | awk '{print$1}')
        if [ "$new_md5" != "$old_md5" ]; then
            [ "$1" = 1 ] || echo "$(eval "$FMT_DT") [Subscribe Rules Need Update]"
            if [ "$X" = 0 ]; then
                rm -f $AD_WORK_PATH/3rd/*
                cp -a $down_tmp_path "$AD_WORK_PATH"
            else
                rm -f /etc/adblock/3rd/*
                cp -a $down_tmp_path /etc/adblock
            fi
        else
            echo "$(eval "$FMT_DT") [Subscribe Rules No Change]"
        fi
    else
        echo "$(eval "$FMT_DT") [$B Failed]"
        echo failed >$AD_WORK_PATH/failed
        [ "$1" = 2 ] && rm -f $LOCK && exit
    fi
    [ "$1" = 2 ] && rm -f $LOCK && exit
    rm -rf ${down_tmp_path%/*}
}

case $1 in
addown)
    down 1
    [ "$X" = 1 ] || rm -f $LOCK
    exit
    ;;
down) down 2 ;;
gen)
    gen
    [ "$X" = 1 ] || rm -f $LOCK
    exit
    ;;
esac

if [ "$(uci -q get adblock.@adblock[0].enable)" = 1 ]; then
    [ -n "$_3RD_URL" ] && down
    update_time="$(eval "${FMT_DT}")" && echo "${update_time}" >$AD_WORK_PATH/adblock.updated
fi

rm -f $LOCK
